- name: Get version information about {{ item | title }}
  ansible.builtin.uri:
    body_format: json
    url: "https://checkpoint-api.hashicorp.com/v1/check/{{ item }}"
  register: response

- name: Download {{ item | title }} ({{ response.json.current_version }})
  ansible.builtin.unarchive:
    creates: "/usr/local/bin/{{ item }}"
    dest: /usr/local/bin
    mode: 0755
    remote_src: true
    src: "{{ response.json.current_download_url.rstrip('/') }}/{{ item }}_{{ response.json.current_version }}_{{ ansible_facts['system'] | lower }}_{{ architectures[ansible_facts['architecture']] }}.zip"
