- name: Get {{ item.name | title }} version number
  ansible.builtin.uri:
    body_format: json
    url: "https://checkpoint-api.hashicorp.com/v1/check/{{ item.name }}"
  register: response

- name: Set {{ item.name | title }} version number
  set_fact:
    version: "{{ item.version is defined | ternary(item.version, response.json.current_version) }}"

- name: Download {{ item.name | title }} ({{ version }})
  ansible.builtin.get_url:
    dest: /tmp
    url: "{{ base_url }}/{{ item.name }}/{{ version }}/{{ item.name }}_{{ version }}_{{ system }}_{{ architecture }}.zip"
  register: artifact

- name: Install {{ item.name | title }}
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    mode: 0755
    src: "{{ artifact.dest }}"
