- name: Install unzip
  ansible.builtin.package:
    name: unzip
    state: present

- name: Include {{ system }} tasks
  include_tasks: "{{ system }}.yaml"
  loop: "{{ items }}"
  loop_control:
    label: "{{ item.name }}"
